<script lang="ts">
import { defineComponent, markRaw } from "vue";
import { useStore } from './store'
import { ethers } from "ethers";
import * as Registry from '../../../artifacts/contracts/RLN_Registry.sol/Registry.json'
import Navbar from "./components/Navbar.vue";

//
declare global {
  interface Window {
    ethereum?: any;
  }
}

export default defineComponent({
  name: "App",
  components: {
    Navbar,
  },
  setup() {
    const store = useStore();
    let contractAddress = "0x5fbdb2315678afecb367f032d93f642f64180aa3";
    // connect to Metamask
    let provider = new ethers.providers.Web3Provider(window.ethereum, "any");
    store.commit('setProvider', markRaw(provider));

    store.state.provider.on("network", (newNetwork: string, oldNetwork: string) => {
      // When a Provider makes its initial connection, it emits a "network"
      // event with a null oldNetwork along with the newNetwork. So, if the
      // oldNetwork exists, it represents a changing network
      if (oldNetwork) {
        console.log(newNetwork);
        window.location.reload();
      }
    });

    // Saves the Signer to the store
    store.state.provider.send("eth_requestAccounts", []).then(() => {
      store.commit('setSigner', markRaw(store.state.provider.getSigner()))
    });

    // Saves the Address to the store for reference
    store.state.signer.getAddress().then((address: string) => {
      store.commit('setAddress', address);
    });

    // Saves the Registry contract to the store
    store.commit('setRegistry', markRaw(new ethers.Contract(contractAddress, Registry.abi, store.state.provider)));

  },

  methods: {
  },
});

console.log("RLN Private Beacon Chain Validator Messaging App loaded");
</script>

<template>
  <Navbar></Navbar>
  <main class="container-fluid main-container">
    <div class="top-section pt-5 pb-4 mb-5 text-center">
      <img class="d-block mx-auto mb-5" src="/images/eth-diamond-rainbow.png" height="120px" />
      <h2>Private message sharing for Beacon Chain Validators</h2>
      <p class="description">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio,
        maiores commodi voluptatem minus similique necessitatibus quis
        perferendis quisquam a provident debitis at magni esse illo aliquid.
        Atque repellat ratione et?
      </p>
    </div>

    <div class="row">
      <div class="left-col col-md-6">
        <h4 class="mb-3">Register</h4>
        <hr class="my-3" />
        <form>
          <div class="col-12 mb-3">
            <label for="pubkey" class="form-label">Public Key</label>
            <textarea
              type="text"
              class="form-control"
              id="pubkey"
              placeholder="0x..."
              maxlength="48"
            />
            <div class="invalid-feedback">Please enter a valid public key.</div>
            <small>BLS public key of the ETH2 validator (48 bytes)</small>
          </div>

          <div class="col-12 mb-3">
            <label for="idCommitment" class="form-label">Identity Commitment</label>
            <textarea
              type="text"
              class="form-control"
              id="idCommitment"
              placeholder="0x..."
              maxlength="32"
            />
            <div class="invalid-feedback">Please enter a Identity Commitment.</div>
            <small>Identity commitment of the ETH2 validator (32 bytes)</small>
          </div>

          <div class="col-12 mb-3">
            <label for="sig" class="form-label">Signature</label>
            <textarea type="text" class="form-control" id="sig" placeholder="0x..." maxlength="96" />
            <div class="invalid-feedback">Please enter a valid signature.</div>
            <small>
              BLS signature of the Identity Commitment generated by the BLS
              public key (96 bytes)
            </small>
          </div>

          <button class="w-100 btn btn-lg" type="submit">Register</button>
        </form>
      </div>

      <div class="right-col col-md-6">
        <h4 class="mb-3">Query Registration Status</h4>
        <hr class="my-3" />
        <form>
          <div class="col-12 mb-3">
            <label for="pubkey" class="form-label">Public Key</label>
            <textarea
              type="text"
              class="form-control"
              id="pubkey"
              placeholder="0x..."
              maxlength="48"
            />
            <div class="invalid-feedback">Please enter a valid public key.</div>
            <small>BLS public key of the ETH2 validator (48 bytes)</small>
          </div>

          <button class="w-100 btn btn-lg" type="submit">Search</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-2 text-muted text-center text-small">
    <p class="mb-1">© 2022 AtHeartEngineer on behalf of The Ethereum Foundation</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="https://github.com/AtHeartEngineering/rln-validator-messaging">Github</a>
      </li>
      <li class="list-inline-item">
        <a href="https://github.com/AtHeartEngineering/rln-validator-messaging/issues">Issues</a>
      </li>
    </ul>
  </footer>
</template>

<style scoped>
main {
  max-width: min(80rem, 100%);
}

.main-container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.top-section {
  border-bottom: 2px solid var(--divider);
  border-bottom-left-radius: 1rem;
  border-bottom-right-radius: 1rem;
}

.description {
  max-width: min(50rem, 100%);
  margin: 1.5rem auto 1rem;
  font-size: 1.25rem;
  font-weight: 400;
}
.left-col,
.right-col {
  --bs-gutter-x: 4.5rem;
  padding-block: 0.5rem;
}

.row {
  width: 100%;
}

.left-col {
  border-right: 1px solid var(--divider);
}

.right-col {
  border-left: 1px solid var(--divider);
}
</style>


<style>
/* Global Styles */

/* Global Variables */
:root {
  --gray: rgb(34, 34, 34);
  --gray-light: rgba(242, 242, 242, 0.6);
  --white: rgb(242, 242, 242);
  --green: #88d848;
  --green-light: #bdff88;
  --blue: #5a9ded;
  --blue-light: #53d3e0;
  --blue-very-light: #a7f6ff;
  --violet: #9198e5;
  --violet-light: #b4bbff;
  --mauve: #cc71c2;
  --pink: #e66465;
  --pink-light: #ff9c92;
  --sunset: #ff7575;
  --sunset-light: #ffb585;
  --yellow: #ffe94d;
  --yellow-light: #fff397;
  --divider: #ff7575cc;

  --btnbg: rgba(0, 0, 0, 0)
    linear-gradient(
      49.21deg,
      rgba(127, 127, 213, 0.3) 19.87%,
      rgba(134, 168, 231, 0.3) 58.46%,
      rgba(145, 234, 228, 0.3) 97.05%
    )
    repeat scroll 0% 0%;
  --btnbg-hover: rgba(0, 0, 0, 0)
    linear-gradient(
      49.21deg,
      rgba(127, 127, 213, 0.5) 19.87%,
      rgba(134, 168, 231, 0.5) 58.46%,
      rgba(145, 234, 228, 0.5) 97.05%
    )
    repeat scroll 0% 0%;
}

body,
html {
  background-color: var(--gray) !important;
  color: var(--white) !important;
  font-family: "Roboto", sans-serif;
}

small {
  color: var(--gray-light);
}

a {
  color: var(--sunset-light) !important;
  text-decoration: none !important;
}

a:hover {
  color: var(--pink-light) !important;
  text-decoration: underline;
}

h1,
h2,
h3,
h4 {
  color: var(--blue-very-light);
  text-transform: capitalize;
  letter-spacing: 0.125rem;
}

hr {
  color: var(--white) !important;
}

label {
  text-transform: capitalize;
}

.btn {
  color: var(--white) !important;
  text-shadow: 0px 0px 16px black;
  font-weight: 500 !important;
  text-transform: uppercase;
  letter-spacing: 0.25rem;
  background: var(--btnbg);
  border: 2px solid rgba(134, 168, 231, 0.2) !important;
}
.btn:hover {
  background: var(--btnbg-hover);
}
</style>